# Migration from helm chart to argocd application eventuellement via ArgoCD UI (import from repo)
# kubectl apply -f k8s/argocd/external-secrets-application.yaml -n argocd --dry-run=server
# # kubectl apply -f k8s/argocd/external-secrets-application.yaml -n argocd
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: external-secrets
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: https://charts.external-secrets.io
#     chart: external-secrets
#     targetRevision: 2.6.0
#     helm:
#       releaseName: external-secrets
#       # values vides pour coller à l'existant (USER-SUPPLIED VALUES: null)
#       values: |
#         {}
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: external-secrets
#   syncPolicy:
#     automated:
#       prune: true       # supprime les ressources retirées du chart
#       selfHeal: true     # corrige automatiquement un drift comme celui qu'on vient de fixer
#     syncOptions:
#       - CreateNamespace=false   # le namespace existe déjà
